name: Winston Chatbot
skillMetadata:
  sections:
    - name: Select a Chatbot
      fields:
        - type: select
          name: chatbot_brain
          label: Botbrain
          options: AnnaL|AnnaL;none|none
          value: alice
        - type: checkbox
          label: Enable chatbot as fallback skill
          name: enabled
          value: "false"
        - type: input
          label: Number of chat lines before saving brain state
          name: save_loop_threshold
          value: 1
